/*
 *  Panther is a program to encode your media files from one format to the other.
 *  Copyright (C) 2012  Sankha Narayan Guria
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */
package sngforge.panther.gui;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.filechooser.FileFilter;
import org.farng.mp3.MP3File;
import org.farng.mp3.id3.ID3v1;
import sngforge.panther.Globals;

/**
 * The ID3 tag editor
 * @author Sankha
 */
public class ID3Editor extends javax.swing.JPanel {
    
    File file;

    /**
     * Creates new form ID3Editor
     */
    public ID3Editor() {
        initComponents();
    }
    
    public void initialize(){
        JFileChooser jfc=new JFileChooser();
        FileFilter filter;
        filter = Globals.createFileFilter("MP3 Music Files",true, "mp3");
        jfc.setFileFilter(filter);
        jfc.showOpenDialog(this);
        file=jfc.getSelectedFile();
        if(file==null){
            Globals.mainFrame.setVisible(false);
            Globals.mainFrame.remove(Globals.scrollPane);
            Globals.scrollPane=new JScrollPane(new MainPanel());
            Globals.mainFrame.add(Globals.scrollPane);
            Globals.mainFrame.setVisible(true);
        } else{
            filename.setText("File: "+file.getName());
            try{
                MP3File mp3=new MP3File(file);
                ID3v1 id3v1=mp3.getID3v1Tag();
            }catch(Exception e){
                System.err.println(e);
                JOptionPane.showMessageDialog(null, e, "Panther - Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        filename = new javax.swing.JLabel();

        jLabel1.setText("The tags in the MP3 file selected are listed below. Edit them and click Save to make the changes.");

        filename.setText("File: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(filename))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(filename)
                .addContainerGap(250, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel filename;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
